---
name: "\U0001F41B Bug Report"
about: Create a report to help us improve Soulpedia's code or CLI.
title: "[BUG] "
labels: bug
assignees: ''
---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Run command '...'
2. Click on '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots / Logs**
If applicable, add screenshots or terminal logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux]
 - Tool: [e.g. Claude Code, Gemini CLI, Web Browser]
 - Version [e.g. 22]